import os
import json
import urllib.request
import re

CATALOG_PATH = r"C:\Users\NOTE-(FORM)02JUL26\.gemini\antigravity-ide\brain\ecaa19f5-7e5b-4118-8cc9-feefc49cd1cc\scratch\drive_catalog.json"
OUTPUT_DIR = os.path.join(os.getcwd(), "public", "images", "totems")
MANIFEST_PATH = os.path.join(os.getcwd(), "src", "data", "totemImagesManifest.json")
TS_OUTPUT_PATH = os.path.join(os.getcwd(), "src", "data", "totemImages.ts")

os.makedirs(os.path.join(os.getcwd(), "src", "data"), exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

with open(CATALOG_PATH, "r", encoding="utf-8") as f:
    drive_data = json.load(f)

# Category mapping
CATEGORY_MAP = {
    "Totens Balcão": "countertop",
    "Totens com Base": "floor",
    "Totens com LED": "led",
    "Totens Parede": "wall"
}

def determine_color(name):
    lower = name.lower()
    if "preto e branco" in lower or ("preto" in lower and "branco" in lower):
        return "black-white"
    elif "preto" in lower:
        return "black"
    elif "branco" in lower:
        return "white"
    return "standard"

def determine_model(cat_key, name):
    lower = name.lower()
    if cat_key == "Totens Balcão":
        return "countertop"
    elif cat_key == "Totens com Base":
        return "floor"
    elif cat_key == "Totens Parede":
        return "wall"
    elif cat_key == "Totens com LED":
        if "parede" in lower:
            return "wall"
        elif "balcão" in lower or "balcao" in lower:
            return "countertop"
        else:
            return "floor"
    return "floor"

def sanitize_slug(name):
    s = name.lower()
    s = re.sub(r'[\(\)]', '', s)
    s = re.sub(r'\s+', '-', s.strip())
    s = re.sub(r'[^a-z0-9\-]', '', s)
    return s

all_images = []
download_queue = []

for folder_name, items in drive_data.items():
    cat_slug = CATEGORY_MAP.get(folder_name, "general")
    sub_dir = os.path.join(OUTPUT_DIR, cat_slug)
    os.makedirs(sub_dir, exist_ok=True)
    
    for idx, item in enumerate(items, 1):
        file_id = item["id"]
        original_name = item["name"]
        color = determine_color(original_name)
        model = determine_model(folder_name, original_name)
        is_led = ("led" in folder_name.lower()) or ("led" in original_name.lower())
        
        # Clean file name
        base_name = os.path.splitext(original_name)[0]
        clean_name = f"{cat_slug}-{color}-{idx}.png"
        local_rel_path = f"/images/totems/{cat_slug}/{clean_name}"
        local_abs_path = os.path.join(sub_dir, clean_name)
        drive_direct_url = f"https://lh3.googleusercontent.com/d/{file_id}"
        drive_view_url = f"https://drive.google.com/file/d/{file_id}/view"
        
        record = {
            "id": file_id,
            "title": original_name.replace(".png", ""),
            "fileName": clean_name,
            "category": cat_slug,
            "modelSlug": model,
            "color": color,
            "hasLed": is_led,
            "localPath": local_rel_path,
            "driveUrl": drive_view_url,
            "downloadUrl": drive_direct_url,
            "width": 1080,
            "height": 1080,
            "aspectRatio": "1:1"
        }
        all_images.append(record)
        
        # We queue for download
        download_queue.append((file_id, local_abs_path, original_name))

print(f"Total images cataloged: {len(all_images)}")

# Save manifest
with open(MANIFEST_PATH, "w", encoding="utf-8") as f:
    json.dump(all_images, f, ensure_ascii=False, indent=2)
print(f"Saved manifest: {MANIFEST_PATH}")

# Generate TypeScript wrapper
ts_content = f"""// Generated by scripts/sync-totem-images.py
// Total photorealistic ambient images: {len(all_images)}

export interface TotemPhoto {{
  id: string;
  title: string;
  fileName: string;
  category: "countertop" | "floor" | "wall" | "led";
  modelSlug: "countertop" | "floor" | "wall";
  color: "white" | "black" | "black-white" | "standard";
  hasLed: boolean;
  localPath: string;
  driveUrl: string;
  downloadUrl: string;
  width: number;
  height: number;
  aspectRatio: string;
}}

import manifestData from "./totemImagesManifest.json";

export const TOTEM_PHOTOS: TotemPhoto[] = manifestData as TotemPhoto[];

export function getPhotosByModel(modelSlug: "countertop" | "floor" | "wall"): TotemPhoto[] {{
  return TOTEM_PHOTOS.filter((p) => p.modelSlug === modelSlug);
}}

export function getPhotosByColor(color: "white" | "black" | "black-white"): TotemPhoto[] {{
  return TOTEM_PHOTOS.filter((p) => p.color === color);
}}

export function getFeaturedPhoto(modelSlug: "countertop" | "floor" | "wall", color?: string): string {{
  const match = TOTEM_PHOTOS.find((p) => {{
    if (p.modelSlug !== modelSlug) return false;
    if (color && p.color !== color) return false;
    return true;
  }});
  return match?.localPath || `/models/cabinet-${{modelSlug}}.svg`;
}}
"""

with open(TS_OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write(ts_content)
print(f"Saved TS helper: {TS_OUTPUT_PATH}")
