// Generated by scripts/sync-totem-images.py
// Total photorealistic ambient images: 154

export interface TotemPhoto {
  id: string;
  title: string;
  fileName: string;
  category: "countertop" | "floor" | "wall" | "led";
  modelSlug: "countertop" | "floor" | "wall";
  color: "white" | "black" | "black-white" | "standard";
  hasLed: boolean;
  localPath: string;
  driveUrl: string;
  downloadUrl: string;
  width: number;
  height: number;
  aspectRatio: string;
}

import manifestData from "./totemImagesManifest.json";

export const TOTEM_PHOTOS: TotemPhoto[] = manifestData as TotemPhoto[];

export function getPhotosByModel(modelSlug: "countertop" | "floor" | "wall"): TotemPhoto[] {
  return TOTEM_PHOTOS.filter((p) => p.modelSlug === modelSlug);
}

export function getPhotosByColor(color: "white" | "black" | "black-white"): TotemPhoto[] {
  return TOTEM_PHOTOS.filter((p) => p.color === color);
}

export function getFeaturedPhoto(modelSlug: "countertop" | "floor" | "wall", color?: string): string {
  const match = TOTEM_PHOTOS.find((p) => {
    if (p.modelSlug !== modelSlug) return false;
    if (color && p.color !== color) return false;
    return true;
  });
  return match?.localPath || `/models/cabinet-${modelSlug}.svg`;
}
